name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Code generation & compile
    strategy:
      matrix:
        os: [ ubuntu-18.04, windows-2019, macos-10.15 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Generate protos and build project (Powershell)
        if: ${{ matrix.os == 'windows-2019' }}
        run: .\build.ps1 -generateProtos
        shell: pwsh

      - name: Generate protos and build project (Bash)
        if: ${{ matrix.os != 'windows-2019' }}
        run: ./build.sh --generate-protos

  tests:
    needs: build
    name: Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tests
        run: |
          touch vars.env
          docker-compose up
          docker-compose --file=cluster-docker-compose.yml up -d
          go test -v ./...
          docker-compose down
          docker-compose --file=cluster-docker-compose.yml down

  linting:
    needs: tests
    name: Linting
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Linting
        run: go vet ./...

      - name: Code formatting checks
        run: diff -u <(echo -n) <(goimports -d ./)